[project]
name = 'Planck-Scale-Physics-Simulator'
description = ''
authors = []
telemetry = true
cache_dir = './.cache'
requirements = []
[contracts.distributed-computing-integration]
path = 'contracts/distributed-computing-integration.clar'
clarity_version = 2
epoch = 2.5

[contracts.incentive-token]
path = 'contracts/incentive-token.clar'
clarity_version = 2
epoch = 2.5

[contracts.planck-phenomena-nft]
path = 'contracts/planck-phenomena-nft.clar'
clarity_version = 2
epoch = 2.5

[contracts.simulation-management]
path = 'contracts/simulation-management.clar'
clarity_version = 2
epoch = 2.5
[repl.analysis]
passes = ['check_checker']

[repl.analysis.check_checker]
strict = false
trusted_sender = false
trusted_caller = false
callee_filter = false
